# Generated by Django 2.2 on 2019-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_auto_20190513_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='solved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
